Split Data Module - remote and repository
hossein69ameri/NewsApi pull request #12
Opened 2024-10-07 05:32 UTC by hossein69ameri

Create remote and repository Module into Data Module

2024-10-07 09:32 UTC, Kaaveh requested changes

2024-10-07 09:32 UTC, Kaaveh commented on data/remote/build.gradle.kts
> +    implementation(project(":domain"))
Don't depend this module on the domain module.

2024-10-07 09:32 UTC, Kaaveh commented on data/remote/src/main/AndroidManifest.xml
> +<manifest />
Delete this file.

2024-10-07 09:32 UTC, Kaaveh commented on data/remote/src/main/java/com/ameri/remote/network/ApiServices.kt
>  import com.ameri.domain.models.ResponseData
Move `ResponseData` in remote module

2024-10-07 09:32 UTC, Kaaveh commented on data/repository/src/main/AndroidManifest.xml
> +<manifest />
delete this file

2024-10-07 09:32 UTC, Kaaveh commented on settings.gradle.kts
> +include(":data")
remove this line

2024-10-07 12:25 UTC, hossein69ameri commented
Delete Unused Files , Fix Gradle , Move Dto to Remote Module

2024-10-07 13:37 UTC, hossein69ameri commented
Delete gitignore

2024-10-14 19:45 UTC, Kaaveh approved these changes

2024-10-14 19:45 UTC, merged