Migrate To Modularization
hossein69ameri/NewsApi pull request #5
Opened 2024-09-18 07:15 UTC by hossein69ameri

Review For Modularization

2024-09-18 09:46 UTC, hossein69ameri commented
Rebase develop onto modularization

2024-09-18 13:03 UTC, Kaaveh requested changes

2024-09-18 13:03 UTC, Kaaveh commented on data/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
Remove this unused file

2024-09-18 13:03 UTC, Kaaveh commented on domain/build.gradle.kts
> +    implementation(project(":data"))
domain shouldn't depend on the data module.

2024-09-18 13:03 UTC, Kaaveh commented on domain/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
Remove this unused file

2024-09-18 13:03 UTC, Kaaveh commented on presentation/src/main/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
Remove this unused file

2024-09-18 13:05 UTC, Kaaveh commented on domain/src/main/java/com/ameri/domain/repository/HomeRepository.kt
>  class HomeRepository @Inject constructor(private  val apiServices: ApiServices) {
Put this class into the data module.

2024-09-18 13:06 UTC, Kaaveh commented on domain/src/main/java/com/ameri/domain/repository/HomeRepository.kt
>  class HomeRepository @Inject constructor(private  val apiServices: ApiServices) {
Rename HomeRepository -> NewsRepository

2024-09-18 13:08 UTC, Kaaveh commented on domain/src/main/java/com/ameri/domain/repository/HomeRepository.kt
>  class HomeRepository @Inject constructor(private  val apiServices: ApiServices) {
Create an interface for this class and put that interface into the domain module (Checkout the ComposeNews's repositories)

2024-09-18 13:10 UTC, Kaaveh commented on data/build.gradle.kts
> +    implementation(project(":app"))
The data module shouldn't depend on the app module

2024-09-28 13:45 UTC, hossein69ameri commented
Please Check RuntimeError  : java.lang.RuntimeException: Cannot create an instance of class com.ameri.presentation.viewmodel.NewsViewModel

2024-09-29 05:38 UTC, hossein69ameri commented
Restore Libraries and MinSDK 23

2024-09-30 14:40 UTC, hossein69ameri commented
Fix DI Crash With Implement data Module in App Module and Add KSP To Gradle Plugin

2024-09-30 15:55 UTC, Kaaveh approved these changes

2024-09-30 15:57 UTC, Kaaveh commented on presentation/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
Is this permission necessary?

2024-09-30 15:58 UTC, Kaaveh commented on data/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
Is this permission necessary?

2024-10-01 10:16 UTC, hossein69ameri commented
Fix Unused Code in Manifest and Unused Dependencies in Gradle

2024-10-01 13:53 UTC, merged